on: push
  # schedule:
  #   - cron:  '37 13 * * 0'

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Scrape magic
      run: |
        # rm questions.md
        # python3 scrape.py
        echo "a" >> a.txt
    - name: Commit and push 
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

        date +%s
        git add questions.md
        git commit -m "Scrape-`date +%s`"
        # git push
